### ISSUE TITLE
Use microlens instead of lens.

### ISSUE THREAD

**Issue by noughtmare** [yi-editor/yi-language#5]
I am trying to convert this package to use microlens instead of lens, but I can't find a way to replace `Control.Lens.Plated` in `Yi.Regex`. Is that even possible @neongreen?

**Comment by noughtmare** [comment]
I have now created an ad-hoc implemetation of only the necessary functions of `Control.Lens.Plated` in `Yi.Regex` in [my branch](https://github.com/noughtmare/yi-language/tree/microlens)

**Comment by neongreen** [comment]
I don't know pretty much anything about `plated`, to be honest. I always thought that you could just use `uniplate` or whatever it's called directly and it would be only marginally less convenient, but I might be completely mistaken.
